const mongoose=require("mongoose")

const adminSchema= new mongoose.Schema({
    role:{
         type:String,
         default:"admin"
    },
    poolname:{
        type:String,
        required:true
    },
    poollocation:{
         type:String,
         required:true
    },
    adminname:{
        type:String,
        required:true
    },
    adminusername:{
         type:String,
         required:true,
         default:"hello"
    },
    adminemail:{
        type:String,
        lowercase:true,
        required:true
    },
    adminmobile:{
        type:Number,
        required:true,
        default:123445667889
    },
    adminpassword:{
        type:String,
        required:true
    },
    poolhourlyrate:{
        type:Number,
        required:true
    },
    gender:{
        type:String,
        default:0
    },
    active:{
        type:Boolean,
        default:0
    },
    adminaddress:{
        type:String,
        required:true
    },
    adminimage:{
        type:String,
        required:true
    },
    isDeleted:{
        type:Boolean,
        default:0
    },
    pertoedithourlyrate:{
         type:Boolean,
         default:0
    },
    createdAt:{
        type:"Date",
        default:Date.now()
    },
    updatedAt:{
        type:"Date",
        default:Date.now()
    }
})
const Admin = mongoose.model("Admin",adminSchema)

module.exports = Admin
